---
- hosts: all
  vars_files:
    - vars/main.yml
  tasks:
    - block:
        - name: Create needed folders
          file:
            path: "/root/{{ item }}"
            state: directory
          with_items:
            - haproxy
            - keepalived

        - name: Deploy haproxy.cfg.j2 template
          template:
            src: roles/haproxy-keepalived/templates/haproxy.cfg.j2
            dest: /root/haproxy/haproxy.cfg
      when: inventory_hostname in groups['load_balancers'] and groups['app_servers'] | length | int  > 1

- hosts: load_balancers
  vars_files:
  - vars/main.yml                                            
  roles:
    - role: haproxy-keepalived
      when:  groups['app_servers'] | length | int  > 1